### ISSUE TITLE
Support for ublpe21

### ISSUE THREAD

**Issue by carlosthe19916** [phax/ph-ubl#17]
The current version of ublpe is using UBL 2.0 but it would be great to include support for UBL 2.1

**Comment by phax** [comment]
Do you have a link where I can find the XSDs and the like?

**Comment by carlosthe19916** [comment]
@phax this a link that contains XSDs for UBL 2.1

[https://github.com/FrameworkPeru/openinvoiceperudocs/tree/master/Documentacion/UBL21/Ejemplos/xsd](url)

**Comment by carlosthe19916** [comment]
@phax Yes you're right they are equal. However, is not possible to use UBLPEWriter with UBL21. For example this code works:
```
oasis.names.specification.ubl.schema.xsd.invoice_2.InvoiceType invoiceType20;
UBLPEWriter.invoice().write(invoiceType20, new File("myfile.xml"));
```
but this does not:

```
oasis.names.specification.ubl.schema.xsd.invoice_21.InvoiceType invoiceType21;
UBLPEWriter.invoice().write(invoiceType20, new File("myfile.xml"));
```

**Comment by phax** [comment]
Yes, because sometimes it is UBL 2.0 and sometimes it is UBL 2.1.
Is it possible for you to use class `UBL21Reader` and `UBL21Writer` from thew Maven artefact `com.helger:ph-ubl21`?
It would be possible to add it to the ublpe package, but that means, that it would depend from both Maven artefacts `ph-ubl20` and `ph-ubl21` which would bloat the result application file size.

**Comment by carlosthe19916** [comment]
I don't think include both artifacts ph-ubl20 and ph-ubl21 is a good idea. I was thinking about creating another maven module called ph-ublpe21 which can include dependencies for ph-ubl21.

**Comment by phax** [comment]
Any action from my side needed? @carlosthe19916
