### ISSUE TITLE
Fill InvoiceType Object from List<Map<String,String>>

### ISSUE THREAD

**Issue by belya1979** [phax/ph-ubl#52]
Dear Sir,
How could we fill InvoiceType Object dynamically from List<Map<String,String>> or resultset or something like that, which comes from database contains all invoice date including invoice lines
Note: the column names in database are same as element names in InvoiceType

**Comment by phax** [comment]
There is no "name" based matching support in ph-ubl. If you want to do something, you need to program it your own e.g. using reflection or so.

**Comment by phax** [comment]
In general I am not a big fan of using name similarities between database objects and Java objects because it creates an unnecessary coupling. If you ever update one or the other, you will have a problem.
Additionally, the structure of an Invoice is a bit too complex to fit into a key-value-pair-list and is easily usable.
So my proposal would be, that you create your own mapper from `String` to `Consumer<String>` that maps from your `List<Map<String,String>>` data structure to the setters in the InvoiceType (e.g. "map "InvoiceNumber" to `invoice::setInvoiceNumber` - I hope you know what I mean). That means you can update the mapping independent from your data structures.

**Comment by belya1979** [comment]
Thanks dear for your suggestion.. I already started making my own mapping classes for invoice, credit note and debit note.
 and thanks also for caring.
