### ISSUE TITLE
Update UBLTR specifications

### ISSUE THREAD

**Issue by phax** [phax/ph-ubl#56]
Based on the thread in https://github.com/phax/ph-schematron/issues/141

**Comment by cemo** [comment]
Hello @phax, do you think that this issue will be resolved soon?

**Comment by phax** [comment]
Nope - no schedule on this one yet. But shouldn't take too long

**Comment by phax** [comment]
New XSD is part of the 8.0 release

**Comment by idilalemdar** [comment]
Since my real question is on UBLTR, I think the correct place for my question would be here (I just posted here, may delete from the incorrect place: https://github.com/phax/ph-schematron/issues/141):

Hi @phax, here again after some 2 years :) 

I also am trying to create UBLTR invoices. I have the following gradle dependencies:

```
implementation group: 'com.helger.ubl', name: 'ph-ubltr', version: '9.0.3'
implementation group: 'com.helger.ubl', name: 'ph-ubl21-codelists', version: '9.0.3'
```

At first, I wasn't aware of the existence of UBLTR either like @cemo and tried to create the invoice using UBL2.1 instead:

```
UBL21Marshaller.UBL21JAXBMarshaller<InvoiceType> ubl21Writer = UBL21Marshaller.invoice();
InvoiceType invoice = createInvoice(ublData);
String invoiceStr = ubl21Writer.getAsString(invoice);
```

where createInvoice is my helper method creating the UBL 2.1 invoice.

Problem is, I need to add UBLExtensions field to the invoice like this:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
         xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
         xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
         xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
         xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"
         xmlns:qdt="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2"
         xmlns:ubltr="urn:oasis:names:specification:ubl:schema:xsd:TurkishCustomizationExtensionComponents"
         xmlns:udt="urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2"
         xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2 UBL-Invoice-2.1.xsd">
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionContent>
                <ds:Signature Id="somesignatureid">
                     ...
                    </ds:Signature>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
```

 However my IDE does not seem to find some relevant UBLTR schemas for UBLExtensions like `QualifiedDatatypes-2`, `TurkishCustomizationExtensionComponents` or `UnqualifiedDataTypesSchemaModule:2`. Therefore adding UBLExtensions and its child fields like above makes the invoice unparseable by UBL2.1 . I then installed ubltr 9.0.3 instead but this did not solve the problem. These xds's are still somehow missing. 

Besides, `UBLTRMarshaller` does not directly include an invoice marshaller like `UBL21Marshaller.invoice()` does, but instead there is something called `UBLTRMarshaller.trPackage()`. That seems to be including invoice as an element but if truth be told, it's a little confusing how to put an invoice into `trPackage`. Is there a more straightforward way like there is in `UBL21Marshaller`  in `UBLTRMarshaller` as well?

Sorry to be commenting on a closed issue, but I thought the context was same so I am writing under this issue. Thank you very much for any help, and my most profound congratulations on developing and maintaining a project like this!

**Comment by phax** [comment]
The problem of your IDE is most likely, that the UBL extension is an `xsd:any` element, which means it is a placeholder in the XML Schema where "anything" can go (of course this can be limited, but that would be out of scope of this introduction).
In general, I would prefer if you open new issues, because otherwise it is easy to create a scope-creep - thanks
